### ISSUE TITLE
How to use ?

### ISSUE THREAD

**Issue by buzzzo** [smart4life/humhub-auth-basic#3]
Hi 

Your work seems to be interesting but how to install and use ?

thx

**Comment by sebmennetrier** [comment]
Hi

For the installation, it's like others modules that are not in humhub catalog. You must extract sources in a module folder (e.g protected/modules/auth-basic). Then enable the module throught admin interface or thanks yii command `php yii module/enable auth-basic`.

When enabled, users that open humhub on browser with the header `Authorization` containing the basic scheme with an existing username/password are directly connected on humhub and so the login page is not displayed.
