### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by buzzzo** [smart4life/humhub-auth-basic#4]
Hi

I'm using your module and it does a wonderful job by providing seamless auth with my SSO infrastructure.

I've not understand if you let the user login by just trusts the http basic header or you also take user and password from auth headers and use them for login in to humhub system.

My impression is that you use the latter (perform "real" login on humhub)

Thx

**Comment by sebmennetrier** [comment]
Hi @buzzzo,

You are right, it performs a real login using the username and password from http basic header.
